# The URL, device ID and API keys are to be filled by you and is not to be shared with anyone
#For Privacy i use 'XXXXXXXXX'
#You can find SSID in your Twilio Dashboard
SSID = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
#You can find AUTH TOKEN on your Twilio Dashboard
AUTH_TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxx'
#FROM_NUMBER,This is the no. generated by Twilio.
FROM_NUMBER = '+xxxxxxxxxxx'
#TO_NUMBER,This is your number
TO_NUMBER = '+xxxxxxxxxxx'
API_KEY = "fxxxxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx"
DEVICE_ID = "BOLTxxxxxxx"
FRAME_SIZE = 4
MUL_FACTOR = 3

#FRAME_SIZE = 10
#MUL_FACTOR = 6
